FORMAT: 1A

# r53ddns API

In this api documentation, the following keywords are used to indicate
the authentication required to access a particular resource:

- **ANON** - no authentication is required to access the resource
- **ADMIN** - requires administrative privileges
- **AUTH** - available to any authenticated user
- **SELF** - available only if the authenticated user matches the
  owner of the resource

# Group Root

## API Root [/]

### Get a list of available API endpoints [GET]

[ **ANON** ] Returns a list of available API endpoints. If a basic
authentication header is passed as part of the request, `{username}`
in the response will be replaced by whatever username was specified in
the header.

+ Response 200 (text/json)

        {
          "endpoints": {
            "credentials": "/user/{username}/credentials/", 
            "host": "/user/{username}/host/", 
            "user": "/user"
          }, 
          "documentation": "http://docs.r53ddns.apiary.io/"
        }

## Client ip address [/ip]

### Get the client ip address [GET]

[ **ANON** ] Returns the ip address of the client from the perspective
of the server.  The service respects the `X-Forwarded-For` HTTP
header, so this should operate correctly behind a proxy server (for
example, when running on OpenShift).

+ Response 200 (text/plain)

        127.0.0.1

# Group User

A user has the following attributes:

- `id`
- `name`
- `password`
- `created`
- `is_admin`

## User account collection [/user/]

+ Model (text/json)

        [
          {
            "is_admin": false, 
            "id": 1, 
            "name": "bob", 
            "created": "2015-04-09 20:56:19.940569"
          }, 
          {
            "is_admin": false, 
            "id": 3, 
            "name": "alice", 
            "created": "2015-04-10 01:48:43.806573"
          }
        ]

### List available user accounts [GET]

[ **ADMIN** ]

+ Response 200

    [User account collection][]

### Create a new user account [POST]

[ **ADMIN** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + username (string, required)
        + password (string, required)
        + is_admin (boolean, optional)
            + Default: 0

    + Body

            username=bob&password=secret&is_admin=0

+ Response 200

    [User][]

## User [/user/{username}]

Operations on a specific user.  `{username}` may be specified as
either a name or numeric id.

+ Parameters

    + username (string, required) - A user name or numeric id

+ Model (text/json)

        {
          "is_admin": false, 
          "id": 1, 
          "name": "bob", 
          "created": "2015-04-09 20:56:19.940569"
        } 

### Get information about a user account [GET]

[ **ADMIN** **SELF** ] Retrieve information about an existing user
account.  Note that the `password` attribute is write-only and will
never be returned via the API.

+ Response 200

    [User][]

### Update password for a user account [PUT]

[ **ADMIN** **SELF** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + password (string, required)

    + Body

            password=secret

+ Response 200

    [User][]

### Delete a user account [DELETE]

[ **ADMIN** **SELF** ] Deletes the specified user account.  If you
delete the account you are using for authentication you will no longer
be able to make use of the API.

+ Response 200

    [User][]

# Group Credentials

A credential set has the following attributes:

- `id`
- `name`
- `accesskey`
- `secretkey`
- `created`
- `owner`

## Credentials collection [/user/{username}/credentials/]

+ Parameters

  + username (string, required)

+ Model (text/json)

        [
          {
            "name": "default", 
            "created": "2015-04-09 20:56:20.066008", 
            "accesskey": "foo", 
            "secretkey": "1234", 
            "owner": 1, 
            "id": 1
          }, 
          {
            "name": "testing", 
            "created": "2015-04-12 17:29:15.705465", 
            "accesskey": "bar", 
            "secretkey": "5678", 
            "owner": 1, 
            "id": 2
          }
        ]

### Get all credentials belonging to a user [GET]

[ **ADMIN** **SELF** ]

+ Response 200

    [Credentials collection][]

### Create a new set of credentials [POST]

[ **ADMIN** **SELF** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + label (string, optional)
        + accesskey (string, required)
        + secretkey (string, required)

    + Body

            accesskey=bar&secretkey=5678&label=testing

+ Response 200

    [Credentials][]

## Credentials [/user/{username}/credentials/{credentials_name}]

+ Parameters

  + username (string, required)
  + credentials_name (string, required)

+ Model (text/json)

        {
          "name": "testing", 
          "created": "2015-04-12 17:29:15.705465", 
          "accesskey": "bar", 
          "secretkey": "5678", 
          "owner": 1, 
          "id": 2
        }

### Get information about a set of credentials [GET]

[ **ADMIN** **SELF** ]

+ Response 200

    [Credentials][]

### Update accesskey or secretkey [PUT]

[ **ADMIN** **SELF** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + accesskey (string, optional)
        + secretkey (string, optional)

    + Body

            accesskey=foo&secretkey=1111

+ Response 200

    [Credentials][]

### Delete a set of credentials [DELETE]

[ **ADMIN** **SELF** ] Deletes a set of credentials. Note that this
will also delete any host entries that make use of the given
credentials.

+ Response 200

    [Credentials][]

# Group Host

A host has the following attributes:

- `id`
- `name`
- `zone`
- `created`
- `last_update`
- `credentials`

## Host collection [/user/{username}/host/]

+ Parameters

  + username (string, required)

+ Model (text/json)

        [
          {
            "name": "host.example.com", 
            "zone": "example.com", 
            "created": "2015-04-12 20:02:39.441219", 
            "last_update": "2015-04-12 23:31:59.742794", 
            "credentials": 1, 
            "id": 1, 
            "last_address": "10.10.10.10"
          }
        ]

### List available hosts [GET]

[ **ADMIN** **SELF** ]

+ Response 200

    [Host collection][]

### Create a new host record [POST]

[ **ADMIN** **SELF** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + hostname (string, required)
        + zone (string, optional)
        + credentials (string, required)

    + Body

            name=host.example.com&credentials=1

+ Response 200

    [Host][]

## Host [/user/{username}/host/{hostname}]

+ Parameters

  + username (string, required)
  + hostname (string, required)

+ Model (text/json)

        {
          "name": "host.example.com", 
          "zone": "example.com", 
          "created": "2015-04-12 20:02:39.441219", 
          "last_update": "2015-04-12 23:31:59.742794", 
          "credentials": 1, 
          "id": 1, 
          "last_address": ""
        }

### Get information about a host [GET]

[ **ADMIN** **SELF** ]

+ Response 200

    [Host][]

### Update credentials used for a host [PUT]

[ **ADMIN** **SELF** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + credentials (string, required)

    + Body

            credentials=2

+ Response 200

    [Host][]

### Delete a host [DELETE]

[ **ADMIN** **SELF** ]

+ Response 200

    [Host][]

## Host address [/user/{username}/host/{hostname}/address]

+ Parameters

    + username (string, required)
    + hostname (string, required)

### Get last host address [GET]

[ **ADMIN** **SELF** ]

+ Response 200 (text/plain)

        10.10.10.10

### Update address for a host [POST]

[ **ADMIN** **SELF** ]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + address (string, required) - This may be an ip address in
          dotted-quad notation, or the string `auto`, in which case
          the address used will be the ip address of the connecting
          client.

    + Body

            address=10.10.10.10

+ Response 200 (text/json)

        {
          "name": "host.example.com",
          "zone": "example.com", 
          "created": "2015-04-12 20:02:39.441219", 
          "last_update": "2015-04-13 01:53:18.375219", 
          "credentials": 1, 
          "id": 1, 
          "last_address": "10.10.10.10"
        }

<!-- vim: set ft=markdown : -->
